# Generated by Django 5.0.7 on 2024-08-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_description_alter_video_title'),
    ]

    operations = [
    ]
