# Generated by Django 5.0.7 on 2024-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_description_alter_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='topic_id',
            new_name='topic'
        ),
        migrations.RenameField(
            model_name='video',
            old_name='subtopic_id',
            new_name='subtopic'
        ),
    ]
